name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bizman-continuous-deployment :

    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run migrations
      run: php artisan migrate --force
      
    - name: Run npm install and compile assets
      run: |
        npm install
        npm run dev
    
    - name: Run tests
      run: php artisan test
