name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bizman-continuous-deployment :

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: composer install
      run: composer install

    - name: Run migrations
      run: php artisan migrate --force
      
    - name: Run npm install and compile assets
      run: |
        npm install
        npm run dev
    
    - name: Run tests
      run: php artisan test
