name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bizman-continuous-deployment :

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Run something
      run: echo "passed"
